export const SAVE_USER = 'SAVE_USER';

export const REQUEST_COIN_SUCESS = 'REQUEST_COIN_SUCESS';

export const REQUEST_COIN_FAILURE = 'REQUEST_COIN_FAILURE';

export const SAVE_EXPENSES = 'SAVE_EXPENSES';

export const DELETE_EXPENSES = 'DELETE_EXPENSES';

export const EDIT_EXPENSE = 'EDIT_EXPENSE';

export const SAVE_EDIT_EXPENSE = 'SAVE_EDIT_EXPENSE';

export const CHANGE_BUTTON = 'CHANGE_BUTTON';
