export const SAVE_USER = 'SAVE_USER';

export const REQUEST_COIN_SUCESS = 'REQUEST_COIN_SUCESS';

export const REQUEST_COIN_FAILURE = 'REQUEST_COIN_FAILURE';

export const SAVE_EXPENSES = 'SAVE_EXPENSES';
